# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
    name = "Projects"
    url = "#projects"
    weight = 20


[[main]]
  name = "Publications"
  url = "#featured"
  weight = 50

#[[main]]
#  name = "Talks"
#  url = "#talks"
#  weight = 55

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 60

[[main]]
  name = "Co-workers"
  url = "co-workers/"
  weight = 60


[[main]]
  name = "Various Posts"
  url = "post/"
  weight = 65

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
